import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "hsl(228, 100%, 84%)",
              borderRadius: 2,
              colorBgContainer: "hsl(206, 94%, 87%)",
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
